version: "2.2"

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail
      MYSQL_DATABASE: mail
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33066:3306"

  postfix:
    build:
      context: .
    ports:
      - "25252:25"

volumes:
  mysql-data:
    driver: local
